<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\host\Tessera.Host\Tessera.Host.csproj"/>
    <PackageReference Include="xunit" Version="2.9.*"/>
    <PackageReference Include="NSubstitute" Version="5.3.*"/>
    <PackageReference Include="Shouldly" Version="4.3.*"/>
    <PackageReference Include="Bogus" Version="35.6.*"/>
    <PackageReference Remove="Meziantou.Analyzer"/>
    <PackageReference Remove="Microsoft.VisualStudio.Threading.Analyzers" />
  </ItemGroup>
</Project>
