<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup/>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\shared\Tessera.Shared.Kernel\Tessera.Shared.Kernel.csproj"/>
    <ProjectReference Include="..\..\shared\Tessera.Shared.Http\Tessera.Shared.Http.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tessera.Modules.Discovery.Unit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Remove="Meziantou.Analyzer"/>
    <PackageReference Remove="Microsoft.VisualStudio.Threading.Analyzers" />
  </ItemGroup>
</Project>
