/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Not Found: the requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Conflict: the request collides with the current state of the target resource. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Internal Server Error: an unexpected server-side failure occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service inventory aggregated from traces + logs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ServiceSummary"][];
                        "application/json": components["schemas"]["ServiceSummary"][];
                        "text/json": components["schemas"]["ServiceSummary"][];
                    };
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Not Found: the requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Conflict: the request collides with the current state of the target resource. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Internal Server Error: an unexpected server-side failure occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceName}/red": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service RED (rate / errors / duration) */
        get: {
            parameters: {
                query?: {
                    StartUnixMs?: number;
                    EndUnixMs?: number;
                    Operation?: null | string;
                    StepSeconds?: null | number;
                };
                header?: never;
                path: {
                    serviceName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRedResponse"];
                        "text/json": components["schemas"]["ServiceRedResponse"];
                    };
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Composite health status across all wired providers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["HealthResponse"];
                        "application/json": components["schemas"]["HealthResponse"];
                        "text/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Not Found: the requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Conflict: the request collides with the current state of the target resource. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Internal Server Error: an unexpected server-side failure occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List logs by trace id (MVP-01). Ad-hoc LogsQL — MVP-02. */
        get: {
            parameters: {
                query?: {
                    TraceId?: string;
                    Stream?: string;
                    StartUnixMs?: number;
                    EndUnixMs?: number;
                    Limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PageOfLogEntry"];
                        "application/json": components["schemas"]["PageOfLogEntry"];
                        "text/json": components["schemas"]["PageOfLogEntry"];
                    };
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Not Found: the requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Conflict: the request collides with the current state of the target resource. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Internal Server Error: an unexpected server-side failure occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Errors inbox: group exception-bearing error traces */
        get: {
            parameters: {
                query?: {
                    StartUnixMs?: number;
                    EndUnixMs?: number;
                    Service?: string;
                    Limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ErrorGroupSummary"][];
                        "application/json": components["schemas"]["ErrorGroupSummary"][];
                        "text/json": components["schemas"]["ErrorGroupSummary"][];
                    };
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Not Found: the requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Conflict: the request collides with the current state of the target resource. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Internal Server Error: an unexpected server-side failure occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search traces by service / operation / time / duration */
        get: {
            parameters: {
                query?: {
                    Service?: string;
                    Operation?: string;
                    StartUnixMs?: number;
                    EndUnixMs?: number;
                    MinDurationMs?: number;
                    MaxDurationMs?: number;
                    Cursor?: string;
                    Limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PageOfTraceSummary"];
                        "application/json": components["schemas"]["PageOfTraceSummary"];
                        "text/json": components["schemas"]["PageOfTraceSummary"];
                    };
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Not Found: the requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Conflict: the request collides with the current state of the target resource. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Internal Server Error: an unexpected server-side failure occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/traces/{traceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Request view: trace + correlated logs (degradable) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    traceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetTraceResponse"];
                        "application/json": components["schemas"]["GetTraceResponse"];
                        "text/json": components["schemas"]["GetTraceResponse"];
                    };
                };
                /** @description Bad Request: request validation failed (model binding or FluentValidation). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Not Found: the requested resource does not exist. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Conflict: the request collides with the current state of the target resource. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Internal Server Error: an unexpected server-side failure occurred. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Bad Gateway: upstream provider unavailable. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Service Unavailable: degraded state (e.g. one or more providers unreachable). */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
                /** @description Gateway Timeout: upstream provider exceeded its timeout budget. */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorGroupSummary: {
            key: string;
            exceptionType?: null | string;
            message?: null | string;
            /** Format: int32 */
            count?: number;
            sampleTraceIds: string[];
        };
        GetTraceResponse: {
            trace?: null | components["schemas"]["TraceDetail"];
            correlatedLogs: components["schemas"]["LogEntry"][];
            mode: components["schemas"]["RequestViewMode"];
            markers: components["schemas"]["LogMarker"][];
            /** Format: int32 */
            erroredSpanCount?: number;
            exceptions?: components["schemas"]["TraceExceptionSummary"][];
            /** @description Per-trace dependency mini-map from CLIENT spans. Null when spans are absent (logs-only). */
            dependencyGraph?: null | components["schemas"]["DependencyGraph"];
        };
        DependencyEdge: {
            /** @description Caller node id. */
            fromId: string;
            /** @description Callee node id. */
            toId: string;
            /**
             * Format: int32
             * @description Number of CLIENT spans that produced this edge.
             */
            callCount: number;
            /**
             * Format: int32
             * @description CLIENT spans on this edge with status error.
             */
            errorCount: number;
        };
        /** @description Per-trace dependency mini-map: unique nodes plus aggregated edges. */
        DependencyGraph: {
            nodes: components["schemas"]["DependencyNode"][];
            edges: components["schemas"]["DependencyEdge"][];
        };
        DependencyNode: {
            /** @description Stable node key (service name, or db:… / external:…). */
            id: string;
            /** @description Human-readable label. */
            name: string;
            kind: components["schemas"]["DependencyNodeKind"];
        };
        /**
         * @description Role of a node on a per-trace dependency mini-map (camelCase wire).
         * @enum {string}
         */
        DependencyNodeKind: "service" | "database" | "external";
        HealthResponse: {
            provider: string;
            status: components["schemas"]["HealthStatus"];
            detail?: null | string;
        };
        /**
         * @description Per-provider health status. `Tessera.Host` aggregates per-provider
         *     reports into a composite endpoint response.
         * @enum {string}
         */
        HealthStatus: "healthy" | "degraded" | "unhealthy";
        /**
         * @description A single log entry. May be correlated with a trace (TraceId? LogEntry.TraceId) and/or
         *     span (SpanId? LogEntry.SpanId). IReadOnlyDictionary&lt;string, string&gt; LogEntry.Fields carries structured key-value
         *     attributes attached at log emission time.
         */
        LogEntry: {
            /** Format: int64 */
            timestamp: number;
            level: components["schemas"]["LogLevel"];
            service: string;
            traceId: null | components["schemas"]["TraceId"];
            spanId: null | components["schemas"]["SpanId"];
            message: string;
            fields: {
                [key: string]: string;
            };
        };
        /**
         * @description Log severity level. Maps to OpenTelemetry LogLevel + syslog severity.
         *                     Member names are the OTel SeverityText spellings
         *     (INFO / WARN), not the .NET
         *     Information / Warning ones. They travel to the wire
         *     verbatim (camelCased) and every consumer — the TypeScript union and
         *     the .log-level-* CSS classes it composes by name — keys off
         *     those spellings, so renaming a member here silently unstyles a
         *     severity in the UI.
         * @enum {string}
         */
        LogLevel: "trace" | "debug" | "info" | "warn" | "error" | "fatal";
        /**
         * @description Timeline marker for a log entry overlaid on a request view.
         *     long LogMarker.OffsetMs is relative to the matched span's
         *     `StartTime` when SpanId? LogMarker.SpanId is set and that span
         *     exists on the trace; otherwise relative to the trace
         *     `StartTime`. When there is no trace (logs-only), offsets are
         *     relative to the earliest log timestamp in the batch (so the first
         *     log sits at 0).
         */
        LogMarker: {
            spanId: null | components["schemas"]["SpanId"];
            /**
             * Format: int64
             * @description Milliseconds from the anchor start (see summary).
             */
            offsetMs: number;
            /** @description Log severity. */
            level: components["schemas"]["LogLevel"];
            /** @description Message preview (full message; FE may truncate). */
            message: string;
            /**
             * Format: int64
             * @description Absolute log timestamp (unix ms UTC).
             */
            timestampUnixMs: number;
        };
        /**
         * @description Cursor-paginated result page. string? Page&lt;T&gt;.Cursor is opaque to clients;
         *     pass it back to the originating endpoint unchanged to fetch the next page.
         */
        PageOfLogEntry: {
            /** @description Items in this page. */
            items: components["schemas"]["LogEntry"][];
            /** @description Opaque pagination cursor, or null if no more pages. */
            cursor: null | string;
            /** @description True when more pages exist beyond this one. */
            hasMore: boolean;
        };
        /**
         * @description Cursor-paginated result page. string? Page&lt;T&gt;.Cursor is opaque to clients;
         *     pass it back to the originating endpoint unchanged to fetch the next page.
         */
        PageOfTraceSummary: {
            /** @description Items in this page. */
            items: components["schemas"]["TraceSummary"][];
            /** @description Opaque pagination cursor, or null if no more pages. */
            cursor: null | string;
            /** @description True when more pages exist beyond this one. */
            hasMore: boolean;
        };
        /**
         * @description Degradation mode for a request view (trace + correlated logs).
         *     FE uses this to show a banner when one source is missing.
         * @enum {string}
         */
        RequestViewMode: "full" | "spansOnly" | "logsOnly" | "empty";
        /**
         * @description OpenTelemetry resource describing the entity that produced telemetry
         *     (typically a process / service instance). Small first-class fields for
         *     the common service identity attributes; remaining resource attributes
         *     live in IReadOnlyDictionary&lt;string, string&gt; Resource.Attributes for project predicates and display.
         */
        Resource: {
            /** @description `service.name` — required service identity (never empty in well-formed data). */
            serviceName: string;
            /** @description Optional `service.namespace`. */
            serviceNamespace: null | string;
            /** @description Optional `deployment.environment`. */
            deploymentEnvironment: null | string;
            /** @description Remaining resource attributes (open dict). */
            attributes: {
                [key: string]: string;
            };
        };
        /** @description A single operation (e.g. endpoint or RPC method) belonging to a service. */
        ServiceOperation: {
            name: string;
            /** Format: int32 */
            count: number;
        };
        /** @description Service inventory summary with aggregated metrics across traces. */
        ServiceSummary: {
            name: string;
            /** Format: int32 */
            spanCount: number;
            /** Format: int32 */
            errorCount: number;
            operations: components["schemas"]["ServiceOperation"][];
        };
        /** @description HTTP body for service RED. Null fields mean unknown for that source. */
        ServiceRedResponse: {
            /**
             * Format: double
             * @description Requests per second, or null when unknown.
             */
            requestRatePerSec?: null | number;
            /**
             * Format: double
             * @description Error ratio in [0, 1], or null when unknown.
             */
            errorRatio?: null | number;
            /**
             * Format: double
             * @description p95 duration in milliseconds, or null when unknown.
             */
            durationP95Ms?: null | number;
            source: components["schemas"]["RedSource"];
        };
        /**
         * @description Whether RED values came from PromQL metrics or span counters (camelCase wire).
         * @enum {string}
         */
        RedSource: "metrics" | "spanApprox";
        /**
         * @description A single span within a trace. May have a parent (SpanId? Span.ParentSpanId)
         *     and child spans (IReadOnlyList&lt;SpanEvent&gt; Span.Events captures span events like exceptions).
         *     string Span.Service is a convenience alias of string Resource.ServiceName
         *     kept for module mappers that still read the flat field.
         */
        Span: {
            spanId: components["schemas"]["SpanId"];
            parentSpanId: null | components["schemas"]["SpanId"];
            service: string;
            operation: string;
            /** Format: int64 */
            startTime: number;
            /** Format: int64 */
            durationMs: number;
            status: components["schemas"]["TraceStatus"];
            kind: components["schemas"]["SpanKind"];
            resource: components["schemas"]["Resource"];
            tags: {
                [key: string]: string;
            };
            events: components["schemas"]["SpanEvent"][];
        };
        /** @description A point-in-time event recorded on a span (e.g. exception, log message). */
        SpanEvent: {
            /** Format: int64 */
            time: number;
            name: string;
            attributes: {
                [key: string]: string;
            };
        };
        /** @description Span identifier (typically 16-char hex per OpenTelemetry / Jaeger convention). */
        SpanId: string;
        /**
         * @description OpenTelemetry span kind (OTLP enum values). Distinguishes server/client
         *     RPC, producer/consumer messaging, and internal work.
         * @enum {string}
         */
        SpanKind: "unspecified" | "internal" | "server" | "client" | "producer" | "consumer";
        /** @description Full trace with reconstructed span tree. Returned by GET /api/traces/{traceId}. */
        TraceDetail: {
            traceId: components["schemas"]["TraceId"];
            rootService: string;
            rootOperation: string;
            /** Format: int64 */
            startTime: number;
            /** Format: int64 */
            durationMs: number;
            status: components["schemas"]["TraceStatus"];
            spans: components["schemas"]["Span"][];
        };
        TraceExceptionSummary: {
            exceptionType?: null | string;
            exceptionMessage?: null | string;
            spanId: string;
            service: string;
            operation: string;
        };
        /** @description Trace identifier (typically 32-char hex per OpenTelemetry / Jaeger convention). */
        TraceId: string;
        /**
         * @description Status of a trace or span, mirroring OpenTelemetry span status codes.
         * @enum {string}
         */
        TraceStatus: "ok" | "error" | "unset";
        /** @description Lightweight trace summary without spans. Returned by GET /api/traces list endpoint. */
        TraceSummary: {
            traceId: components["schemas"]["TraceId"];
            rootService: string;
            rootOperation: string;
            /** Format: int64 */
            startTime: number;
            /** Format: int64 */
            durationMs: number;
            status: components["schemas"]["TraceStatus"];
            /** Format: int32 */
            spanCount: number;
            services: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
