<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup />
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.0" />
    <PackageReference Remove="Meziantou.Analyzer" />
    <PackageReference Remove="Microsoft.VisualStudio.Threading.Analyzers" />
  </ItemGroup>
</Project>
