<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup/>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Tessera.Shared.Kernel\Tessera.Shared.Kernel.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.4.1" PrivateAssets="all" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.*" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Remove="Meziantou.Analyzer"/>
    <PackageReference Remove="Microsoft.VisualStudio.Threading.Analyzers" />
  </ItemGroup>
</Project>
