namespace Tessera.Modules.Preferences.Application;

/// <summary>
///     Per-user UI preference entry — key/value store keyed by
///     <see cref="UserId" /> + <see cref="Key" />. A row carries the
///     JSON-serialized <see cref="ValueJson" /> payload; the schema
///     for each <see cref="Key" /> is enforced by the FE consumer
///     (e.g. <c>"theme"</c> → <c>"light"</c> | <c>"dark"</c>),
///     not by EF Core. Multi-tenant rows (ADR-0001 §11 stretch)
///     will read <see cref="TenantId" /> through
///     <c>FilterHelpers.TenantScoped&lt;T&gt;</c>.
///     <para>
///         MVP-01: idempotent on <c>(UserId, Key)</c> — values are
///         the latest write. Soft-delete via <see cref="DeletedAt" />
///         mirrors every per-module entity; deletes do not free the
///         natural key.
///     </para>
///     <para>
///         Property names stay PascalCase on the entity; EF Core's
///         <c>IEntityTypeConfiguration&lt;T&gt;</c> renames each column
///         to snake_case (per <c>csharp/ef-core.md</c> §3). EF never
///         sees EF data annotations — the Fluent API owns table /
///         column / length / nullability / indexes.
///     </para>
/// </summary>
public sealed class UserPreference
{
    /// <summary>Default tenant id for MVP-01 single-tenant deployments.</summary>
    public const string DefaultTenantId = "0";

    /// <summary>
    ///     Stable identifier. Generated by the application (string
    ///     identity, e.g. <c>"prf_" + Guid.NewGuid().ToString("N")</c>)
    ///     — preference rows are small and we avoid SQLite's auto-
    ///     increment semantics on a write-light table.
    /// </summary>
    public string Id { get; set; } = "";

    /// <summary>
    ///     Owning user. Default <c>0</c> when the request is
    ///     anonymous (Guest scheme) so the row can still be looked
    ///     up; <c>sub</c> claim when authenticated.
    /// </summary>
    public string UserId { get; set; } = "0";

    /// <summary>
    ///     Preference key — e.g. <c>"theme"</c>, <c>"language"</c>,
    ///     <c>"filter_window_minutes"</c>. Length-bounded by EF
    ///     configuration.
    /// </summary>
    public string Key { get; set; } = "";

    /// <summary>
    ///     JSON-encoded value. The schema is per-key and enforced by
    ///     the FE consumer. We persist it as <c>jsonb</c> for
    ///     queryability even though current reads project to
    ///     text — the column type still gives us introspection.
    /// </summary>
    public string ValueJson { get; set; } = "";

    /// <summary>Tenant scope. MVP-01 always <c>"0"</c>.</summary>
    public string TenantId { get; set; } = DefaultTenantId;

    /// <summary>Creation timestamp (UTC unix ms decoded by EF).</summary>
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Last write timestamp (UTC unix ms decoded by EF).</summary>
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>Soft-delete marker — null means active row.</summary>
    public DateTimeOffset? DeletedAt { get; set; }
}
