<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\host\Tessera.Host\Tessera.Host.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.*" />
    <PackageReference Include="xunit" Version="2.9.*" />
    <PackageReference Include="NSubstitute" Version="5.3.*" />
    <PackageReference Include="Shouldly" Version="4.3.*" />
    <PackageReference Include="Respawn" Version="6.2.*" />
    <PackageReference Remove="Meziantou.Analyzer" />
  </ItemGroup>
</Project>
